### ISSUE TITLE
Foundry support?

### ISSUE THREAD

**Issue by rhlsthrm** [dethcrypto/TypeChain#638]
I see that the latest release 7.0.1 is supposed to support foundry/forge artifacts. In my forge project I'm running Typechain but getting an error:

```
Error occured:  _k.match is not a function
Stack trace:  TypeError: _k.match is not a function
    at extractBytecode (/Users/rahul/dev/projects/midasprotocol/monorepo/node_modules/typechain/dist/parser/abiParser.js:221:70)
    at Ethers.transformAbiOrFullJsonFile (/Users/rahul/dev/projects/midasprotocol/monorepo/node_modules/@typechain/ethers-v5/dist/index.js:55:58)
    at Ethers.transformFile (/Users/rahul/dev/projects/midasprotocol/monorepo/node_modules/@typechain/ethers-v5/dist/index.js:30:21)
    at runTypeChain (/Users/rahul/dev/projects/midasprotocol/monorepo/node_modules/typechain/dist/typechain/runTypeChain.js:54:82)
    at async main (/Users/rahul/dev/projects/midasprotocol/monorepo/node_modules/typechain/dist/cli/cli.js:49:20)
```

**Comment by krzkaczor** [comment]
this looks like a problem with monorepo structure... few ideas:
1) can u ensure that ALL typechain related packages are in newest version?
2) reinstall waffle if you use it (it depends on typechain)

**Comment by kulkarohan** [comment]
getting @rhlsthrm's error as well. all related packages are updated, not using waffle

**Comment by rhlsthrm** [comment]
> getting @rhlsthrm's error as well. all related packages are updated, not using waffle

Let me know if you can figure it out. This is still an issue. I cannot reproduce outside of the monorepo though.

**Comment by krzkaczor** [comment]
@rhlsthrm can u share a link to repro? I'll make sure that this is fixed this week.

**Comment by rhlsthrm** [comment]
I just tried to repro again with a minimal example and updated all the packages and it actually worked! It seems like `waffle` actually got a new release to update their deps.

**Comment by mfw78** [comment]
This issue should be re-opened as multiple people have reported this same problem, with the issue still being present.

For what it's worth, on a fresh repo, using the latest versions of `forge 0.1.0 (77882ab 2022-03-22T00:12:56.848059114+00:00)` and `typechain (7.0.1)`, the following error is present:

```raw
yarn typechain-generate --show-stack-traces                                                                    [07:57:35]
yarn run v1.22.17
$ typechain --target ethers-v5 --out-dir typechain "./out/**/*.json" --show-stack-traces
Error occured:  _k.match is not a function
Stack trace:  TypeError: _k.match is not a function
    at extractBytecode (/home/user/src/other/node_modules/typechain/dist/parser/abiParser.js:221:70)
    at Ethers.transformAbiOrFullJsonFile (/home/user/src/other/node_modules/@typechain/ethers-v5/dist/index.js:55:58)
    at Ethers.transformFile (/home/user/src/other/node_modules/@typechain/ethers-v5/dist/index.js:30:21)
    at runTypeChain (/home/user/src/other/node_modules/typechain/dist/typechain/runTypeChain.js:54:82)
    at async main (/home/user/src/other/node_modules/typechain/dist/cli/cli.js:49:20)
```

**Comment by krzkaczor** [comment]
Reopening for now. @mfw78 please prepare repro. We are about to release new major version which should make things slightly better.

**Comment by krzkaczor** [comment]
I found the issue. It should be fixed in next release.

**Comment by mfw78** [comment]
@krzkaczor thanks, sorry workload yesterday prevented the repro. Glad you found the issue, I'm happy to test a PR if you wish :+1:

**Comment by kulkarohan** [comment]
@krzkaczor working now! thanks for the fix.
